# -*- coding: utf-8 -*-
"""ICTd1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15e8GuGC5osXPIP7jX9RXrz8i621RKC-s
"""

# prompt: simple calculator which accepts an expression with two operands using eval by reading the expression from the user with a class

class SimpleCalculator:
    def __init__(self):
        pass

    def calculate(self, expression):
        try:
            result = eval(expression)
            return result
        except SyntaxError:
            print("Invalid expression. Please enter a valid expression with two operands and an operator.")
            return None


calculator = SimpleCalculator()

expression = input("Enter an expression: ")
result = calculator.calculate(expression)

if result is not None:
    print(f"Result: {result}")
else:
    print("Invalid expression.")

